AllCops:
  Exclude:
    - test/**/*
    - spec/**/*
    - db/**/*
    - config/**/*
    - bin/**/*
    - Rakefile
    - Gemfile

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifierOfIfUnless:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
