language: ruby
cache: bundler

rvm:
  - 2.6.2

services:
  - postgresql
  - redis-server

script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
