language: ruby
cache: bundler

env:
  - TWILIO_ACCOUNT_SID:
      secure: "ir8MGxo0VOftcuFHinVVZdstdH8NrH/NTWVnFLrQluNzjZ43ws2kMeZmcicHkgq/+l234GpyLAe8ziRDJ5od2f56wjH73oYCoOX1UJg9b7RErfKAKJd7Ll46YeOB8t4fWsAuu5fWtSechvE5hD8Dm62ErHgq/fsl/
  WveGC0YhtjyTy2cnmgIAtDD28t3DUk1hoF1P+xq62RiOvgrrsQEAQOewKLM+ufSdzht6Vr1kjqW4D3dxgTb2b42Fn/ZU7xS1buKauEGiQtAIWUm4QsDv++52J3g55YqZ0IleYaCehlHvynR2Fs8NDUm0HOhLjHjJujVnt6mF7Yg+
  nO7TP5EYrMkdO75EYKttP0fzLxN741AeJr9rlSFwWdiDaBTMLg6/RoafvqRivJewqbWrVC8YzX81nX7VWa+45uGNEaOwKciUk/fXVdKXDe7M8lTOG4ZgsBd0HYJX26V8fMq+l+E5zycxaI3YwlQTlBgTJEG0Kkj9zGZdtot4k0RP
  5Q8OUA/YxiECA80UzCwCshBnJ2mCdENJN6hG9RQ72bAvteq4gCmpXPdzIvGB2UW2yE4PHDxrV46zWjPIP+qsKcvU7knV5eRLXpsn6IzPS459NMhoIPzzRAlw7oGpZWgGS8URcJAxNQbOpSXTa2/SFq7JCYPBmXf6dE6mzN5gBVWw
  oklCyA="
  - TWILIO_AUTH_TOKEN:
      secure: "nWiGiHo+h3RcDEHIrLJPlMRd1VgvJl9R0sTaMdoXfowFD9LcK5XRL+mGWBybjAp1Gs7olgNKGhyVXhkLlsylfV2y8/r10kwNpDWRB4pjB6YoELYIJxTN0yH+8PUYFU+Fn9CXoQyAndLN7FUDaLwyRdnEnLhmEuUdk
TclTelfQejE+IsYI4MS+cQYoFdoIJMPE6FgybxBqUmbkCmXAKPklICpQabAkVjxmpvvQRYZ7R0xvQHu5yIITcA4j27dS3vGHHJVraPvyGuloPX0sx1RhBF7fyRd39rgp6hg2fl+JmiVcGd1hWeNHaodDKGullYcuQM8svJjPIRQF
lnIupoO0IPGqiUAWSzQP99LtZDWa7jFN12EftDW0O18POtubgmiuxC3hW2R4THBm82DndCX8kA+Blmlzox1XcUAOAv/u97op/Z8RWrTBGi9iumqvI9A2qEQJTo9jFHXBuWo1sbE+vEdigqrYMqzfJtcLCRpKFzOtVPjBM7ukUB1B
cJqwEslkw4ALgrOClmizLn9AyW03adqGYyGYyFKogZfGZ9y3Ij6iKHtKi010k8pg4RO/an3QbCwx378llTnSOyEUFf4XPG0BuNh3csHwjL1AoNNzDNAzbjLQKoU5I47OMia7WnnngkY34Q/GqouUgyhm9QSwRDki8o4bPO/rRV7s
gznRQY="
  - TWILIO_PHONE_NUMBER:
      secure: "VGk8fpTQc+Q4mP6A8csU0eHz9yabGPvn7+BpvqZu6/1Xg4AtANQhSVkgrc3GBXciabZ98wgxiES2EASc6I7KygSN/wPCHSEp2K1nxFmVPG/RNAnSSyHPrWlepy5pOSJbgsWyWL33SJmpaRmZ3Hw/5BXJEMJCDRVEx
L+yWJZtLlMMz0Xe8t2Jv1a8vjOz98a6b+TnKKb6RzNlcxd5Q7dLFc3E4HyKQ72IC8r92nbKHgxCT9DjkO4tBcz4JxJW+UZ23MGSX4L8qQtwMIYBnWuDU+7nRvFPUKAKkOe6Ap7ZP3GtUQH2Zpcu4Xao0MrkxpOfYZxkjdXLcpfFg
nSwyDE25R7TT0MZuFWZV7+5PPDJ8hLk175IkX7JOrjW/jX4pWFV+5XA+pAs2k9h/wyoSP+7MNLUPKggS712P4ZaQJbcF1PHgkIFH0sua2NsnRmTrfSdNuZvDPxBd9RpU7UmFJWufHgNOBLijZ/J0taD18x9AdiMsEhhTWXLYETbv
ctU5odH11+jTF/aUjFmZGdjWLb/RmN9FWSYO9dfxQum/NXqNqJ7KD/YlPAi59yj9766mwsfOHkyzZugbPrGmr/t8uEHukP4vMlRLY1dtKv7MUC2yO8CXCcAPFD9sz8T1V6qLnHi7LveraljXU3Qnhleedgv6Ax+0lpGMsxtXuulO
mjOf7Y="

rvm:
  - 2.6.2

services:
  - postgresql
  - redis-server

script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
