language: ruby
cache: bundler

rvm:
- 2.6.2

services:
  - postgresql

script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - redis-server
  - bundle exec rspec
